export const GET_CODEX_REQUEST = 'GET_CODEX_REQUEST'
export const GET_CODEX_SUCCESS = 'GET_CODEX_SUCCESS'
export const GET_CODEX_FAILURE = 'GET_CODEX_FAILURE'

export const GET_GAMES_REQUEST = 'GET_GAMES_REQUEST'
export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS'
export const GET_GAMES_FAILURE = 'GET_GAMES_FAILURE'

export const SEARCH_CODEX_REQUEST = 'SEARCH_CODEX_REQUEST'
export const SEARCH_CODEX_SUCCESS = 'SEARCH_CODEX_SUCCESS'
export const SEARCH_CODEX_FAILURE = 'SEARCH_CODEX_FAILURE'